"""Init

Revision ID: 8b15a24a2b23
Revises: 
Create Date: 2024-07-10 11:35:41.449584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b15a24a2b23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('hashed_password', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name='user__email_uc'),
    sa.UniqueConstraint('username', name='user__username_uc')
    )
    op.create_index('ix__user__username', 'user', ['username'], unique=True)
    op.create_table('account',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='accountstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_account_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index('ix__account__name', 'account', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__account__name', table_name='account')
    op.drop_table('account')
    op.drop_index('ix__user__username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
